export { default as CalcImage } from '../../../utils/images/calc.jpg'
export { default as CryptoImage } from '../../../utils/images/crypto.jpg'
export { default as CryptoChart } from '../../../utils/images/crypto-2.jpg'
export { default as EmiImage } from '../../../utils/images/houses.png'
export { default as SavingImage } from '../../../utils/images/save.jpg'